version: '3'
    
services:

    main:
        image: puffinrocks/mastodon:latest
        command: bundle exec rails server -p 3000 -b '0.0.0.0'
        ports:
            - 3000
        depends_on:
            - db
            - redis
        volumes:
            - main_assets:/mastodon/public/assets
            - main_packs:/mastodon/public/packs
            - main_system:/mastodon/public/system
            - main_private:/mastodon/private
        env_file: env
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
            - LOCAL_DOMAIN=${VIRTUAL_HOST}
            - SMTP_FROM_ADDRESS=mastodon@${VIRTUAL_HOST}
            - STREAMING_API_BASE_URL=ws://streaming.${VIRTUAL_HOST}:4000
        networks:
            - front
            - back
            - default

    streaming:
        image: puffinrocks/mastodon:latest
        command: npm run start
        ports:
            - 4000
        depends_on:
            - db
            - redis
        volumes:
            - main_private:/mastodon/private
        env_file: env
        environment:
            - VIRTUAL_HOST=streaming.${VIRTUAL_HOST}
            - VIRTUAL_PORT=4000
            - LOCAL_DOMAIN=streaming.${VIRTUAL_HOST}
            - SMTP_FROM_ADDRESS=mastodon@${VIRTUAL_HOST}
        networks:
            - front
            - back
            - default

    sidekiq:
        image: puffinrocks/mastodon:latest
        command: bundle exec sidekiq -q default -q mailers -q pull -q push
        depends_on:
            - db
            - redis
        volumes:
            - main_system:/mastodon/public/system
            - main_private:/mastodon/private
        env_file: env
        environment:
            - LOCAL_DOMAIN=${VIRTUAL_HOST}
            - SMTP_FROM_ADDRESS=mastodon@${VIRTUAL_HOST}
        networks:
            - back
            - default
  
    db:
        image: postgres:alpine
        volumes:
            - db_data:/var/lib/postgresql/data

    redis:
        image: redis:alpine
        volumes:
            - redis_data:/data

volumes:
    main_assets:
    main_packs:
    main_system:
    main_private:
    db_data:
    redis_data:

networks:
    front:
        external: 
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
